language: node_js

node_js:
  - '8'
  - '10'

sudo: false

branches:
  only:
    - master

# before_install:
#   # GUI for real browsers.
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

script:
  - yarn build
  - yarn test

after_success:
  - codecov #运行codecov
  - bash <(curl -s https://codecov.io/bash) -t 4050092d-f86f-46ba-9077-9cbead709950